### ISSUE TITLE
Only reason i believe the error is with CreeperHeal 7.0.0. The server works without it....

### ISSUE THREAD

**Issue by DaDMaR** [nitnelave/CreeperHeal#33]
[2016-12-01-2.log.gz](https://github.com/nitnelave/CreeperHeal/files/623074/2016-12-01-2.log.gz)

Only reason i believe the error is with CreeperHeal 7.0.0. The server works without it....
I first thought it was one of the libs - not passing on info - found temp working solution for me.

Thanks for reply DaDMaR777

**Comment by nitnelave** [comment]
According to your logs, it seems that the problem comes from Vault. It's trying to load the old bPermissions plugin, and failing.

**Comment by nitnelave** [comment]
After some digging around, I was able to reproduce your error, and it seems that Vault picked up an old dependency of CreeperHeal that was still around and considered it a plugin. However, when trying to load that plugin, it couldn't find it, thus the error. It'll be fixed in the next version

**Comment by nitnelave** [comment]
The new version 7.0.1 should fix the issue.

**Comment by DaDMaR** [comment]
thank you...... bad  bad vault ......... thanks again
