### ISSUE TITLE
Problem if server shut down

### ISSUE THREAD

**Issue by TheChampTF** [nitnelave/CreeperHeal#35]
Hey

So for testing, I did blow up some land and watched it as it started coming back.

Seams to work even if people disconnect and comes back later to that area. Big F1 for that.

Now to the part that's sad. If the server shutdown/crash it don't keep any cache of the blocks etc. and don't generate anything back, to how it was. Any chances this can be fixed?

**Comment by nitnelave** [comment]
Hey,

If the server shuts down, during the shutdown process, CH forces the write of all the blocks (i.e. they all get replaced).
However, I don't have something planned for if the server crashes. I would like to avoid a dependency to an sql table or anything similar, so some options would include write each explosion to a file and deleting the file when we're done with the explosion, and in case of crash check the leftover files, but it feels awkward. Do you often get server crashes?

**Comment by TheChampTF** [comment]
Hey,

Not sure what went wrong then, as there was still broken land after the shutdown of the server.

And more for safety if a griefing team came by, better safe than sorry for the crash.
