### ISSUE TITLE
Doors

### ISSUE THREAD

**Issue by TheChampTF** [nitnelave/CreeperHeal#36]
Hey

For some reason the doors come back a bit odd.

You can use top/bottom of the door, but not it all as one door.

After some time it brakes and gives you *2 doors, so you end up having 4 doors if you started with 2.

**Comment by nitnelave** [comment]
Can you give me:
- Minecraft version
- bukkit/spigot version
- CH version
- type of door
- type of explosion
- any suspicious log from CH?

**Comment by TheChampTF** [comment]
1.11.2
Newest CH version
Was a oak door
Tnt
Nope sadly not

**Comment by Jeppa** [comment]
Hi,
same here...
MC 1.11 and 1.11.2

**Comment by Max604** [comment]
Still an issue

**Comment by nitnelave** [comment]
I'm sorry, I have to look into it, but first I need to find time for that.

**Comment by nitnelave** [comment]
Sorry, money is not a problem, but time is :)

**Comment by nitnelave** [comment]
Fixed in 7.0.3
