### ISSUE TITLE
not regenerating :(

### ISSUE THREAD

**Issue by suburbannoize** [nitnelave/CreeperHeal#37]
mc 1.11.2
spigot 1.11.2
pl: coreprotect, asyncworldeditinjector, worldedit, plugman, dispensator, modifyworld, worldborder, lockette, multiverse-core, worldguard, advancedportals, asyncworldedit,extrahardmode, permissionsEx, multiverse-netherportals, vault, griefprevention, essentials, uskyblock, jobs, perworldinventory, silkspawners, ontime, chestcommands, essentialsgeoIP, randomteleport, enjinminecraftplugin, statz

I tried disabling different plugin checking for interference but I can't figure out why its not working.

commands reply but don't show any action

**Comment by nitnelave** [comment]
Hi,

I don't know all the plugins, but you might want to find plugins that prevent modifications to the world, or that replace explosions. My guess is that something like griefprevention replaces the explosions by fake explosions to avoid destroying precious stuff, so CreeperHeal doesn't see any explosion.

**Comment by suburbannoize** [comment]
bit the bullet and went thru one by one disabling and figured out extrahardmode was blocking it.
thanks for your time and help

**Comment by nitnelave** [comment]
Thanks for your efforts. If I have time, I'll try to see with the devs of extrahardmode if we can make it work together. I'll keep this issue open as a reminder.
