### ISSUE TITLE
Cant Find the Sound Option

### ISSUE THREAD

**Issue by zmarotrix** [nitnelave/CreeperHeal#38]
I used to use this plugin and it would make a sound every time a block reappeared but I can no longer find the setting for this. was it removed? it was my favorite part of the plugin.

**Comment by nitnelave** [comment]
In the config.yml file at the root of theCreeperHeal configuration folder, you have (or you can add) the following section:

```
sound:
  volume: 1
  type: ITEM_PICKUP```
