### ISSUE TITLE
Duplication when healing

### ISSUE THREAD

**Issue by gerardvanschip** [nitnelave/CreeperHeal#39]
I recently found that the plugin does a double heal. 

**Example:**

1. Put down a chest with stuff, iron, gold and diamond block placed next to it.
2. Blow up a creeper.
3. 60 seconds later all things heal and are back
4. 15 seconds later it looks like it wants to heal again resulting in all things that were inside the chest to float on the ground and the blocks also float on the ground.

Obviously, this is a massive problem as users can now place valuables, invite a creeper over to blow up and duplicate their stuff.

**Comment by gerardvanschip** [comment]
I have recorded a video to show the problem.
https://www.youtube.com/watch?v=D98ZRdSU3SA

**Comment by nitnelave** [comment]
Can I have your server version and CH version?
Do you have any error message in the logs?
Do you have any other plugins installed?

And btw, thanks for the nice video with the little music and the text effects :)

**Comment by nitnelave** [comment]
Cannot reproduce? I need more information. Feel free to re-open the issue.
