### ISSUE TITLE
Outdated Repo

### ISSUE THREAD

**Issue by Max604** [nitnelave/CreeperHeal#40]
Hello,

could you please update the GitHub repo to 7.0.3 so I can edit a bit of it?

I was just going to add support for special blocks to be exploded, like iron doors and then make some blocks not regen or drop.

Thanks,
Max

**Comment by nitnelave** [comment]
Sorry, I forgot to push, I'll try to do that tonight.

By the way, if you want to do something like that, do a pull request, with a configuration option with a list of blocks to explode and another one with a list of blocks we shouldn't regen.
