### ISSUE TITLE
Is there a way to allow block damage in a world guard region?

### ISSUE THREAD

**Issue by NolanSyKinsley** [nitnelave/CreeperHeal#53]
Title says it all, is there a way to allow block damage and stop healing in a worldguard region when creeperheal is enabled for that world?

**Comment by nitnelave** [comment]
erm... I'm not exactly sure what you mean. But you can disable WG's handling of explosions, and let CH do its job instead, is that what you're looking for?

**Comment by NolanSyKinsley** [comment]
No, I want to have a worldguard region that allows block damage from explosions and creeper heal to not heal the damage.

**Comment by nitnelave** [comment]
Ah, sorry, no, that's not possible currently. I don't interact directly with WG.
