### ISSUE TITLE
A Lot of Errors

### ISSUE THREAD

**Issue by Techno3600** [nitnelave/CreeperHeal#55]
https://pastebin.com/ByC7sqe7
Please fix this ASAP it errors almost every 10 seconds and spams the console.

Latest Spigot 1.12.2 build

Thanks
Techno

**Comment by nitnelave** [comment]
Hey there! Glad that you're enjoying my plugin :)

Just a couple of things:
- This is a free, open-source plugin. You didn't pay anything for it, nor do I expect you to. It works on the basis of good will and free time. I have a short supply of the second, and after your message, I'm running out of the first one as well.
- This plugin has been only very sporadically updated in the past years, as was repeatedly said in the forum/issues/wherever I could post. I'm not actively updating this plugin anymore, and I don't keep up with minecraft updates. But the good news is, it's open source! You could learn some programming and give back to the community, or find someone willing to file a PR to fix the bug. I'll gladly to the reviewing, merging, and deployment process (which also takes some of my time, by the way)
- You don't *have* to use this plugin. In the same way, I don't *have* to fix your bug.
- Again, it's open source! :)

Cheers, and a happy new year!

**Comment by Techno3600** [comment]
Sorry about the message, I still thought this plugin was receiving updates.

**Comment by nitnelave** [comment]
No, no, that's not the point. The message is good, it's always useful to tell a developer or a community the issues with a project :) And even if the plugin has not been really updated in a while, I might put in the effort to make an update if I'm feeling like it at one point, or if somebody else wants to do it.

My point was just that behind most non-huge open source projects are just normal people, that have a life and hobbies, and that talking nicely to them often goes a long way. And of course, if you want to contribute, you'll always be welcome!
