### ISSUE TITLE
Fails to Load after PaperSpigot Update

### ISSUE THREAD

**Issue by SioWolf** [nitnelave/CreeperHeal#56]
After updating to Paper Spigot Build # 1287 I get this error when starting me server:

https://pastebin.com/DunYQEdc

**Comment by nitnelave** [comment]
Are you sure your download is not corrupted? Try downloading again, or try another version.

**Comment by zachbr** [comment]
This was a [Bukkit bug](https://hub.spigotmc.org/jira/browse/SPIGOT-3721) that has since been [fixed](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/20971610daa5cbe1685ac9ba0fa93525e7158048). Updating your server will fix the problem.

**Comment by nitnelave** [comment]
Thanks @zachbr !
