### ISSUE TITLE
Explosions created by other plugins not regenerated

### ISSUE THREAD

**Issue by Programie** [nitnelave/CreeperHeal#57]
I have written a [plugin](https://github.com/Programie/ExplosiveMobs) which calls `createExplosion()` on the world to trigger an explosion but CreeperHeal doesn't heal that type of damage.

Is it possible to also heal such explosions? I'm not sure whether the Minecraft Server actually triggers any event in case of a call to `createExplosion()`.

**Comment by nitnelave** [comment]
Hello,

Have you tried setting the "custom" explosions to true? (in addition to Creepers and TNT).

**Comment by Programie** [comment]
You are right, "custom" was set to `false`. I previously changed it to `true` but it seems that a reload of the plugin using `/ch reload` overwrites the world settings with the currently loaded values making a reload useless. Only stopping the server, changing the config and starting the server again works for me.
